version: "3.0"
services:
  example:
    build: .
    image: "learningdocker:2"
    container_name: example_1
    volumes:
      - type: bind
        source: ./data
        target: /media/data
    command: >
      sh -c "conda run --no-capture-output -n test_env python example_time.py"
  example_2:
    build: .
    image: "learningdocker:2"
    container_name: example_2
    volumes:
      - type: bind
        source: ./data
        target: /media/data
    command: >
      sh -c "conda run --no-capture-output -n test_env python example_time2.py && tail -f /dev/null"

