#!/usr/bin/bash

# The Docker daemon binds to a Unix socket instead of a TCP port. By default that 
# Unix socket is owned by the user root and other users can only access it using sudo. 
# The Docker daemon always runs as the root user.

sudo groupadd docker
sudo usermod -aG docker $USER

sudo reboot