#!/usr/bin/bash

echo "Enabling GPU for Docker"
# Pre installation of nvidia-container-runtime
# https://docs.docker.com/config/containers/resource_constraints/#gpu
curl -s -L https://nvidia.github.io/nvidia-container-runtime/gpgkey | \
    sudo apt-key add -
distribution=$(. /etc/os-release;echo $ID$VERSION_ID)
echo "distribution: $distribution"
curl -s -L https://nvidia.github.io/nvidia-container-runtime/$distribution/nvidia-container-runtime.list | \
    sudo tee /etc/apt/sources.list.d/nvidia-container-runtime.list
sudo apt-get update
curl -s -L https://nvidia.github.io/nvidia-container-runtime/gpgkey | \
    sudo apt-key add -

# Installing nvidia-container-runtime
sudo apt-get install nvidia-container-runtime -y
hook=$(which nvidia-container-runtime-hook)
echo "hook: $hook"
expected_hook="/usr/bin/nvidia-container-runtime-hook"
if [ $hook == $expected_hook ]
then 
    sudo systemctl daemon-reload
    sudo systemctl restart docker
    docker run -it --rm --gpus all ubuntu nvidia-smi
else
    echo "nvidia-container-runtime installation was unsuccessful"
fi


# How to enable gpu on Docker compose:
# https://docs.docker.com/compose/gpu-support/
