#!/usr/bin/bash

# installing cuDNN
# # Download this: https://developer.nvidia.com/rdp/cudnn-archive
    # Download cuDNN v7.6.5 (November 5th, 2019) for CUDA 10.1
# # and then do this:
# intalling cuda
sudo apt install nvidia-cuda-toolkit -y
tar -xvzf cudnn-10.1-linux-x64-v7.6.5.32.tgz
sudo cp cuda/include/cudnn.h /usr/lib/cuda/include/
sudo cp cuda/lib64/libcudnn* /usr/lib/cuda/lib64/
sudo chmod a+r /usr/lib/cuda/include/cudnn.h /usr/lib/cuda/lib64/libcudnn*

# Export CUDA environment variables
echo 'export LD_LIBRARY_PATH=/usr/lib/cuda/lib64:$LD_LIBRARY_PATH' >> ~/.bashrc
echo 'export LD_LIBRARY_PATH=/usr/lib/cuda/include:$LD_LIBRARY_PATH' >> ~/.bashrc
source ~/.bashrc

sudo reboot
